{
	"data": "ENC[AES256_GCM,data:gF4R20bbPdtq2V+VcltkSsULXBrq8OoHvuIstXlsPHV/PKi4817fJ47+Xj98h0CwB+KaZHSck3ZIro+Am/oYPLN6hdSuLg==,iv:V1ageJbk/KC76LL5XKvOYfikGSxB7nCzB67f5+4Rovk=,tag:M5zAqL4rjdQQAtlmyg802g==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOXVabklnaS9qcmpYU1lw\nRGdJZmtOL3BDTERqMTV1RmpKa2pOeHdxVTE4CkpHR1E0ZXg1Ujh5UjhyeStXVGdH\nWlROL2FqSlpjRStyeEc5ZzhITDgzNnMKLS0tIEpPTGoreXpsdlc2Z0JILzNoT0c5\ndkluWlhGT05INzNBS2ZlUEVBRS9XSGcKYOtEZSb5WtT26f6aJMcz1FRo12IYK/G+\nSZcQwOtgcNW5XZ49x/8wHgZzVtwfWnYqRDtEL2/hDNeXZ2vmSRQxrw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-19T06:23:39Z",
		"mac": "ENC[AES256_GCM,data:yzA19Kto7DnQRKhXOxk90DZstOn8uUBncL801+BM9fUHc44UGIxDo4P3gvuI8WTSOnD0WvehhNHwgPLhMWDh6nhx1KMWxDeH5VIa5LcNeFaSpH37+G6ogkuSqVbkJGH2TMy79GV12YpboX4W55yBPrjuCN0jzOlVxeW2F9zOZHQ=,iv:DZcDletxtGKTfOlFyOokjoyoAzeU+ZlzdQ6BnaQjZLU=,tag:oXmWlVzPVg1iMVMaoOea1Q==,type:str]",
		"version": "3.12.1"
	}
}