{
	"data": "ENC[AES256_GCM,data:o4QNe0bqbI6iI7TJEz1iDHETiP+b+X7xCYdixYyCKR0aBH/sYYrCgpOrJlQxpezARkYGSYiO2zk6OjDmIhM3zJvfeDvHpg==,iv:sNl0Ax+RKxmXM23bHd1evB8DZeXXaboKmOCdwP0/oOM=,tag:558ISak4O1xMEFJzzp/TmQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNXN0NzNhczZmTWVDVTg4\neHN3WXZVSEZ6ejYwTnY5Q2pDMklYVkdNcjB3ClVFcmEyVDBkdGVxS0wyNER4eHZq\ncmVqSXUzajYrSzhhL3RnOHZvTGtkVXcKLS0tICtjOEtUZFVvOXkyYkdGVHREZDJW\nSWd1NHJkNzhFaGhtRGdIQlJPT0ZVTDAKI77MreCmyV1aaxT0z+vmL6uSGQtIUdV+\nf6Nk/CJTY1L+Kbow4S26QZcT6FnIwU0z/HvBiGsXR+vww6QXWG9+jg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-17T13:46:16Z",
		"mac": "ENC[AES256_GCM,data:Ho5BYuxuxB8wI2vX3sgDsvdkm/9IZo1ZParWr47efj97QQRwVv2vj5wJEu773cqZcPflUtJbYGTDpS5YPM34AgutHAbyYSh96EOFDHJWKafELwZlbEZC3xj87B0sMaMN6bvQfImphk2DmIGgH3HenVCb/s6bidLemumF+NKRFAU=,iv:2AJjLyWNMt9kVwPTnTJk5VBQ/XDqOCjA+DlloLI1UaU=,tag:12OPDwxkceu4Lf4IZrkPfQ==,type:str]",
		"version": "3.12.1"
	}
}