{
	"data": "ENC[AES256_GCM,data:AoKElra0Vq+GCcpnqOPVOxryUg+MqFK82BToWbHUTc8Z1u4X1x+RrszOj0liDFYuyZm7FzYhIfEIcNLiFS0tU/qTA2ZAEg==,iv:nigZQNPHFwwetcChykMhCdH9/KEHw8MweeXzuNWGXyU=,tag:4zPOwIGqRy2ccV07qWMv8Q==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q2RDS1R1clJINEZQeWJB\nbHpjMkIvT2wvT2o4dWpLRWtoMVUwcnFJZGprCnFPWk94UmY1YzJTWHRMMXlUZXNJ\nRmZhdXRMUkQzbjZaOTg3QUxtendEY1EKLS0tIHd4LzRMU1NMdkNHSWtQRkQ1eU4v\nd2MxNERlOXR4UEV4QU80OWlNUVBnSlUKkmYiQOFrzNz2KV7PmlgNrIHXo29VMtX+\nvUjALGRwnce0NJItBeVGqEEHI4b+CEkoHu4E88FzQIsxOZwbjgk38Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-19T08:48:14Z",
		"mac": "ENC[AES256_GCM,data:pLaFIfk+E5X/hPduJU5624glhhaM+Nu1XKvcKm8Yto9uklG+XRK9XdjJU+jQnVt/OM2npXlTgXN+QGPlC5jT0pcfW9RBPPf6JaIMrLkzH0omxSgCWDTKl2PusRGQLygZ+BcD/ThzYMw+1mmKkIptENP/LPyji28EuXMTsbuByT8=,iv:3uZNy5dbCe694MC9yskbpFFjs2cL5gRiIW2ob7yavOI=,tag:3ksc5YNNl5QIaDren9UUZQ==,type:str]",
		"version": "3.12.1"
	}
}