version: ENC[AES256_GCM,data:Srjsmr+d,iv:Q/SSoT3pzeS091oGuYqJEqlr+zWCu2N2oIMPvvrwt44=,tag:cGSfEuT/tIAyWUuEiapiXg==,type:str]
cache: ENC[AES256_GCM,data:aGCdsQ==,iv:JH9l/ORc+9RWPaeQja15Bf6T3ekjktefrPK/uRWRor8=,tag:TBCiA1YleUluH3Z/SXuxpg==,type:bool]
endpoints:
    custom:
        - name: ENC[AES256_GCM,data:6S12xatxL+0=,iv:cvAsq3Y/WTie/FW1unHBvQGMsEe+mq/RrrEKeDfCMgA=,tag:vVJqWWKLjhU8x3BvlZmT3g==,type:str]
          apiKey: ENC[AES256_GCM,data:9Np1H4kf69TpSSoaYYgGx36zHg==,iv:Uay0GAHNDaNWghi5RM38mfAWydsdR7u+m3B2EWGlupo=,tag:SBJsrjhlOqOOjTlmwNjw6Q==,type:str]
          baseURL: ENC[AES256_GCM,data:we4Ee4KfVv+0EkBVgB0SnONEMCFg3aplh1aZ,iv:qYbDl+RuPONm5E2l0DEICkHe+0HbN/bubMlQUFaXUjU=,tag:ioIrfJUrQMEEy5Gem1ldMg==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:AO/htT9/h9s=,iv:qtPJ1V048rxRTRBqgNQCH8kfMZBF/wVnZfodr/6Pvu4=,tag:90T/MxTcho2EFnCtegJPpQ==,type:str]
          titleConvo: ENC[AES256_GCM,data:4F32Qw==,iv:u/zHguAMvx0SVtZD7ELaCKJAwiecry7wFeQefZQFl2Y=,tag:A7amFeWGXREhj/kNjUHJRg==,type:bool]
          titleModel: ENC[AES256_GCM,data:n2y4kwxiefAAPdSup5/YerI=,iv:viqy+stzEPPAopmDE+xe5cSqHwhO8aBvlP8Xb4+MvJg=,tag:uZguYN5AxpiMm2jaBHw6pQ==,type:str]
          models:
            fetch: ENC[AES256_GCM,data:3b/uLA==,iv:IWc/g4GRJKobamsMPnvyKMYuxX/R9JVkjFceHR00h3k=,tag:Oy7gXA+bFXR1MZGGwB7dQw==,type:bool]
            default:
                - ENC[AES256_GCM,data:FkuPvPfxDHmFCPX6aEM/GBc=,iv:uwqHTifVpbh0PzGVlZweZ10kXWQOU2vCCNDaVJJ4mSQ=,tag:S76rbHD59gmOtZexhaCRgw==,type:str]
        - name: ENC[AES256_GCM,data:hleEKCf2vRWOZ2M=,iv:Rcnd/NmtkdCT3rm4t0p7PH/D3OQKB6wXdDRAkLQWi6I=,tag:Gg2FOF+bYUhsL5ygRVMPGg==,type:str]
          apiKey: ENC[AES256_GCM,data:ndf/DGm2uScYIomohKRZtMm52A==,iv:S54fKxxAzfFZBvJqF6r37uKRvsg2TGT3+OxOk3KiIKg=,tag:ALpnMUaTMAKF53YdPLZg3A==,type:str]
          baseURL: ENC[AES256_GCM,data:OOHGX8lvnBaxgeBIpffFv8xRfqi6Km/uQ8+mznY=,iv:hbQpA3tYPj7ce/UXY02dbhfDl/Btw6SRCZvAy7LJmrc=,tag:JtOsEJTpMRp5IIoS6MYmpA==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:Mdc+J04DCtC66bE=,iv:HVo2D0xG9p14T2AmD4+JQhGYvbbeWQd7VRk3QxcVKnQ=,tag:nlGlwCyxDa4wy50bMKP7fw==,type:str]
          titleConvo: ENC[AES256_GCM,data:yiWuHw==,iv:DdKvh+w7Hzxlig7PHJTNW/jyAftZish89IB0sz3gfHc=,tag:UChHlDFnjUjm8ZrJ8NkPlg==,type:bool]
          titleModel: ENC[AES256_GCM,data:DgS9KR4RLLyKbrQnqmEsiu4=,iv:HD/hml0Gf4yHmfMCoBAsq/LAHKvoWkw37tCc4oMZoyQ=,tag:YzLGAGLj4plJJkz/B6ME9w==,type:str]
          models:
            fetch: ENC[AES256_GCM,data:h2/LWA==,iv:0ZQFdistsQycawwpxD/x+etNAKZGqSCjoKJja2bffas=,tag:bTIrBOeiFfrXllJ2N+j4dw==,type:bool]
            default:
                - ENC[AES256_GCM,data:QM9kQ8FKWkixVrcTCZrG3tI=,iv:md+/QF0+VIgHdPID4JKX+u0xdbglvUUPcXueHa49uZw=,tag:nkvVJHxRJvqjbSC5UVcvWg==,type:str]
        - name: ENC[AES256_GCM,data:S5QljKic7/8paQ==,iv:Kfqp7y7Qb8PJs6pBTIaQynFUfat3mfG/oyfIzwxFhXI=,tag:yeCIiGQTeoE0ZLXONVWBJA==,type:str]
          apiKey: ENC[AES256_GCM,data:fTTHfaMWDre2TIaCH4Fb/oY=,iv:OZ4qMAb3LMNKHLm9tgQLetv2IpF5LAmTQheeNjtpSCo=,tag:uGIJPuL0FhDsw1lLTi7Ykg==,type:str]
          baseURL: ENC[AES256_GCM,data:nbZAmfo4DKFEYR/Z9hGG7WBx/g9L/vhjdDEiEw==,iv:qHZJAUiGgwZQi/dV/eDrHV9jDi+7c4MejaYGQSIZcx8=,tag:mkwA3GwvuyXBRvibOY1rCw==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:kLMRHK/B5s0cPw==,iv:6GAEWROP8FeotWQepH17b8sXiLuy/gMMFgIUaOWzYGQ=,tag:WJtY7yuTmPMs93QRIdxeAw==,type:str]
          titleConvo: ENC[AES256_GCM,data:smYZ2Q==,iv:1Qt6DbHpSvc1L+mtIWcJa4JVQDMw8DlUWHCh+Ps3upU=,tag:y9dz/k2TZXdFVtd7yEzIJQ==,type:bool]
          titleModel: ENC[AES256_GCM,data:J4W4jEcBS5W4JxRlS0vgy/yMlIgEIvwo3II=,iv:fEEXuPtzS25zaYVJq+s9xZQu0C9sO6Ep768coQ0OVfQ=,tag:Gm9uJQCH4/phgAfkzAL9sg==,type:str]
          dropParams:
            - ENC[AES256_GCM,data:OdDc+g==,iv:exFAcfxeI16xovxvcXxFfe4X1tLZCnww+VWqA+chhWs=,tag:HU7+xF+7FVtNwwC+w4wvig==,type:str]
          models:
            fetch: ENC[AES256_GCM,data:5u0q3A==,iv:9dBZio8gJeYkyBpMgQD861talDuIK5TXWkI+ybj8JOM=,tag:HrTlshX4Z72y2sugvOEA8g==,type:bool]
            default:
                - ENC[AES256_GCM,data:Y6PsmVOoNpEJqNjyIaVQkESFRZC9UOn3Eg8=,iv:S4FUKZ6z9HmPT7f2KnGUq7Tii7ufrnhpH88lTIOoXUw=,tag:dDj96mWHyYz+bZUQGVVORw==,type:str]
mcpSettings:
    allowedDomains:
        - ENC[AES256_GCM,data:0VVwXvI13oa7Sw==,iv:B8HolDhzsgJQsQ5hbCwwfy5xKq5sL1piDBAoamPhlHI=,tag:t6b+YEE9lbCEp2ITjYLVfA==,type:str]
        - ENC[AES256_GCM,data:Zeq0vSxBik4hwE0m,iv:6ykAVIM4mU5uPg8qCsC1ei//UPj+hDa+XUsiwKhsFQ8=,tag:t5fIs+pBuY/ARET+WP3wuA==,type:str]
        - ENC[AES256_GCM,data:AgLffWVRLuanvNNi5A==,iv:HbcYWMmZQui5VxUzWAKFt96RQvpV2482p1dzFwYadM8=,tag:3eAsJjW4OqxHVh44zvp/tA==,type:str]
        - ENC[AES256_GCM,data:A4S6rFUMBIAlcyW97ad4,iv:tU60Uj31++uL3wN4N4tS4YxTfefVFjoNPWVp6WO46QE=,tag:hXpHQ44k6ROo40OilshtsA==,type:str]
        - ENC[AES256_GCM,data:4uQSorvietROSw==,iv:FfQJl9p6fkEgYO3Hm2rGVH6aBDevS7dXUJ0Y4BV20f0=,tag:kW5xaa+w/+25proxStswtQ==,type:str]
        - ENC[AES256_GCM,data:j6rxp9kBi9F+F5Um,iv:zVGch3aArvYeO30vbPzYv4UpiHrF8eAsSrf4vYqkynE=,tag:Np7GKBOcFfh5TrKrgRxoUA==,type:str]
        - ENC[AES256_GCM,data:l1W3MZdHfHUS1A==,iv:PtVyNI8yMJ/d9/dyjVQzN8xCvNYRauTfywUZSbNKN1Q=,tag:+1pw2uN67dHVWJeGaVbwjg==,type:str]
        - ENC[AES256_GCM,data:3+uB7UhB/MgL6iYf,iv:hVeIh3mpOSAefeVWbESjfK8Fnn1OnFhO0cT1cPycjMQ=,tag:/G5WjUWRdU7s6RxY3HtqcA==,type:str]
        - ENC[AES256_GCM,data:EkGYZ4JpLZ+QMg==,iv:s/aI3BQco6F4O/1BxounxbW+JuCJd8cszuJph7Vcvl8=,tag:tdC/6F1bJBA1yg//Lug5nQ==,type:str]
        - ENC[AES256_GCM,data:YB81KNV/dyRGgy2s,iv:nJIpaz6GUsmiPDK8FdWU2VB73cciwI8H0lxzVdYKqwo=,tag:ORPzQ478HmQ+2GpW2v5a3A==,type:str]
        - ENC[AES256_GCM,data:PJDzciP8Fc+wbg==,iv:lvDvxcwzRyWRc9uZ7YzRylXD2ywfNRiRriqNHPVNVXU=,tag:569AY7pZAKFIRHmtY0g7og==,type:str]
        - ENC[AES256_GCM,data:STA2TMYQVK/461dV,iv:X3toAChbzTdgGDYZMv/M/h+YeyKW874LopY2ykGx018=,tag:r8ZJbjNaZF3Uk9wHkmN5zA==,type:str]
        - ENC[AES256_GCM,data:ui4p5Suq79D0NaKGBg==,iv:1lu1b0Nf1eYhZpEj46VTtrkO7PxjOUUrGdtpquiUEuI=,tag:ZwRnpA9gIWlHKEYahL78KA==,type:str]
        - ENC[AES256_GCM,data:ksFHJMLpgx4MiWQ0qKhH,iv:PWRI0puM1aHw1vXeIpJPTJICN5t2HVGKIHESZ7zBdvk=,tag:lVokjG0r5yNVX9a+GNhk1A==,type:str]
        - ENC[AES256_GCM,data:AUIZdgj0qc35m0Q=,iv:pKyFNGplb6PfxQJnF2K+IYiAW/ZElUyjGgUtS1Y3Pes=,tag:bFT4hGCgzvdeY9wxxyFNaw==,type:str]
        - ENC[AES256_GCM,data:7PabKilH8O+efg6JeQ==,iv:pcptM9QVaLNWpRUTqwA+n8inPj1eOQyKkxKy/eqHz8M=,tag:0biDm8lfQ5fW65q8RwhrtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTzNmU2x2bnBqRTY2TjFh
            MGs0dDAzaDI5bDlXcVJLbHhBa1c0SzBqT0QwCk5zTEFQaHBJR3YvczRuc1NxZUpT
            RnFQV2xnOFZZTVZlM0xTQ0Q3djV3QzAKLS0tIEd2TFpYL3RWbStCblJ1NzJWUXdM
            YWJCSjBOV01yN0o5OWN2dXAwaXZTVzAKrU13v38lDsgKDmeFt18kPJblxziyN4fP
            PAdUIwGYRyz1OSQrB1kcpXQKXS676MpInCcugPesjjbAPxz+RBWA1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd
    lastmodified: "2026-06-10T22:55:10Z"
    mac: ENC[AES256_GCM,data:hGKjH3LdoxtD8urw8s5oJcrIttSKIdS5dERM4JRH/xxsU3Ad29aS9+uUoEyFb/xOj5wJHLBNxqd7EaEcePvCkh/PyaOTN2vf/OK7wN9pE6o/S4J1NXFRy2IXMzpp+ASeqadcx4YnleSDha/Abo3+RSDO9EcztUfAAIrYXEZrD7Y=,iv:NdmxPcT1rGWOOlnpaHufaDjs4ctq/99B7eOpuhFHcvk=,tag:K+jzX/5Tcck28hwNcI8S2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
