version: ENC[AES256_GCM,data:ORnCflRg,iv:LHPOP5VgHzCtBRTBkkRGKQqQzpjAmnGB3Wb7bzU4FAo=,tag:mihCPYzyi7Ewg50v5gT1WA==,type:str]
cache: ENC[AES256_GCM,data:9VetHw==,iv:kJhKUdkDLdHejFewE0YI5OhaW1lXn13W6ODGlU2LyUI=,tag:wPt2ZmWsgVLcqzVJWeFmWg==,type:bool]
mcpSettings:
    allowedDomains:
        - ENC[AES256_GCM,data:gw==,iv:0AoHPjVOz6kUlCkrJz7L7SscU8tHAuVyo+KKmNOQlEc=,tag:0i1ecWf+TIKwgNwQZzs8Ow==,type:str]
endpoints:
    custom:
        - name: ENC[AES256_GCM,data:SZ8dVoVaUU4Aje8=,iv:6+Fs3Wb8c253S7Z758Q7B9bwq+68wlELwYzZ2zN/UXQ=,tag:9gDrVeN3oDqSgGCeFTh/NA==,type:str]
          apiKey: ENC[AES256_GCM,data:0vdlNCGqswfvA+6gW1RkfIDgww==,iv:62xvF4QCwS26t0ugKgpS2p4kgdux2AmqNQmDwi4aslY=,tag:1dnveSgQe+WHnXaKs2pQxQ==,type:str]
          baseURL: ENC[AES256_GCM,data:NFwTXEpK92jHvmwS1REG1VPqLH4ViQ1REYxfDtU=,iv:XfK7MsuxvKSa8E+sbcacZIBm4uSxyYRwbio5+evP0wY=,tag:A5EqHGtS2f/rloRHSw4Cwg==,type:str]
          models:
            default:
                - ENC[AES256_GCM,data:kOeLxlhbnabR8d0=,iv:QS7rW3bpEp28E1MOPOJ9DbUA8G9yKUljdlxvQ5zom4U=,tag:p6W5A4xFXoYUMwEyqAKz7Q==,type:str]
            fetch: ENC[AES256_GCM,data:qKQi9w==,iv:aWSrKA1vExfLlr0oTm8YLfqPNS+XY3cf2s2+VQPJxn0=,tag:n28a8S2ew7oIE/xyoWDEHA==,type:bool]
          titleConvo: ENC[AES256_GCM,data:giubkg==,iv:8xDBV/WAOFiRs7tVRSfoFJkKMY+iLlepTbtuwF+PIA4=,tag:gY0pitvSkfyUqp7gCQRzSw==,type:bool]
          titleModel: ENC[AES256_GCM,data:FLXcnEhnpV3ZREI=,iv:WxUfQfYbZBQT+UKx8HNKVFYbOhs4to/GbLu38lv3oQU=,tag:/KSRGUMb/xrdghe7w/eBfQ==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:rbIO+uweM/Ulvpo=,iv:z77yNhHf/vozOZFsZXH4lBynqD/52Cv/OLKjG0ILSwU=,tag:JL/Hng8JU3HKdod3Qsi0Ww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVGl2N21kT1M2cWhUalRZ
            QkNMSVppdHdMVU9LTDhXL2pZYTFPT2tsSUZnCjlRVG1YY2FJaUZIOGU0R1d3UXEy
            OW9WNjkzWFQ2S1kyQTJjb0hqY0hCaHcKLS0tIG5rSjJCTkZiVWZEaGY4Tjh6eDBv
            RGRSU1BYSWZYOVlvRk9VNENYamtGY1UKb1u79IM2bjynoKYBEHJ6k1rdA40OnFGQ
            RlacVbSnlrQi2+ILGoSE7H7TRxUrkqJzRt5gmGZG6MWI8QQM80rNrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd
    lastmodified: "2026-06-10T11:35:41Z"
    mac: ENC[AES256_GCM,data:a1FEQ3NJRNVk9Q5dWU0Rd1NCqNC9WsenO2O/hstIS/hkIrsh66uwOeRwWoXUxsuQy1Ajn3Fdp2Jnwr7zGqadp1pw21ErPvzIXqUYY2XOLCddxsrIVU1UKUQPp0+L/aBEL5CbMLop8UvFljcd3PlrMcRVO3piJ5G+V3XivcW8m44=,iv:bcsmYK/Rk6YWcjx1caOoI1v+81ZP/bHwuGZv/m3cFng=,tag:IZ+Pjf6/JacS+IKKMuo3kQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
