{
	"data": "ENC[AES256_GCM,data:/dpnvfLlFOQ9Xh0j4h7B2vB0j5VpHsC9sFBgPW0ZGVEtkumu65ShQj2wcA==,iv:d/DKK0HwMgSfP8tEPaATnRyR33NJisZWRQ5mCp6Weik=,tag:oUAL+2mbeyqcgFHm4EizEg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXV0FCbHg5eDd0ajJxTElq\neTdiQmoyRXZvYmVKQ1UrQldPeGtjRFRud2s0CnlRQW9scmFsTDRGYm1DRmVTcmN3\nVFhRL2J5Z015V0ZWeklUcFR6ZVpUcWcKLS0tIFJscjdlS1VxUmh6cVZOd21xYytS\nOGNjaURGRE5HNkREaHZHM1NCYU1uZWcKOY3nsRJUheGh3TxsA3dKx2yiLtpP/QnS\n118nKKnG9scZ0ZIPpAOLIWsoDJQ6nTi/rywJmSSvDXYPeP8odBClNA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-12T03:03:46Z",
		"mac": "ENC[AES256_GCM,data:5Fni1BGstynbXLB+RdooKcYrNas1ak57eox6eLU48XybI/nbiHOHkVvVJxHzRCWItIirpmQ6hfWsYxsteJqg6mq3Ro29fpKpY7LLKzOBtCO04YY8u6x2/DidYk0UYTIe+UJPczuB+sGpq4bP7UmDVguZah43uG5yRu0e0/n9Dtw=,iv:3i5ASMTLOKGkJkpnwmJcw4oKoERL8obBqJEqmx+Y5p0=,tag:0uSbWuvz+HN0uXZQNKgYcw==,type:str]",
		"version": "3.12.2"
	}
}
