{
	"data": "ENC[AES256_GCM,data:yu7841oe8oov5G8C2AaD8/sRG5cJrLBxJMlD5yyFQeKWz+WXR3VetMwnlQ==,iv:2LcY0BYmK2JHNOLR2JIRd+ujOlG/1nBZBWyxKhQVNpE=,tag:4XiH6jJiQupQV+MKMnxncQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTHdRTCtlY2duUzJ2YXhL\najhyaEx6ZDZsS0RhNjRQdnJ2ZmM0WEJCb1M0ClNNaXluejJvK0ZVSVgzank4bHpN\nbjc0S0l2TUpGUGJNVktmZXorNDBtazgKLS0tIFUwYlVEZm4yTGdveU11QnMxbVFH\nR0RRL1U3NGIrVFI3TTFHZkNQbytOSGMKaJByrvSqs8aWLICnFnClc61yUNYu17EE\nc9OValugYEkJCMcQlNrzyKD0Wrgvj3+GSzC1IMc8+pFT4KvD2AaOmQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-06-12T04:59:37Z",
		"mac": "ENC[AES256_GCM,data:vrrTGE/mYU2QFCAi5JqgrLJVxVAe2kCKnm7N4iIH4l/XgTmQXJmoSU11CiY3HH3O9Qe469KOss90n8KRa263z/Qn8PaGz98dOXqs2kaNka8eyuU3XIdcfVWRfWwPA2QTfJ9cUlngYX2q7wRP6LCP51Z808mIeMgsc3lydc8iEZQ=,iv:/brPkjMJr0zgRd1VfqQbRz1ueZ6ldYn6E5saX8mFUKI=,tag:2bcU4rpUHy4vevwoboeQOQ==,type:str]",
		"version": "3.13.1"
	}
}
