{
	"data": "ENC[AES256_GCM,data:Eti+HC785HHqE3qCqFr336F933msuzSzCnyE67SKrVEZBn63OAFejNk9LA==,iv:uBfRxqDdmvq48ADYWJcJOm1XfI2sya/9J85+YNN7g3k=,tag:bG+hz9RHGMfHvHFWhP865A==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbXZMTUZvcnNGdGdIUnk1\nNUJtbmhsUWxzN1o4bmVhWnJ5amR2NUhOSGk4CnVWNi9GVmpPMnJmNlZTVzlvd24y\nRTl0V3pmcnNHNllVNmdPWVJKeURLVjQKLS0tIGZJL21FQjdzMEhEQkZlRDVNSUhw\nZmQ5RHNUODYzSWpqenBQUVZFNEZvNjgKyVOZbP6ctW+7Hx5ty/Ra5lTXl3oe2X5E\nB6VcjIffgLsa3tt/2BzPflvVW1I/yQKCxI+d1TowVvUDtBR+Etsuvg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-12T11:40:10Z",
		"mac": "ENC[AES256_GCM,data:IAhTHg1dLO30KDhfgzmjItxwoY+CErUwS5L+/kAIQuf2YCluRYIRlY1YFLHh8SMnqMbKAdjc3g8WK/3MzLJ/6pWpRvsBoOiQAupZhLSYtFeLWjHDIzPUzKqmhMg59/8+s1z3f3KzK/ZmPmO3lB92PB0saoLAlT/1ZVDhepicCoU=,iv:ck0zK06r4oa2K0lKjRN5qOfMl+8ZpLoAR9kzOVoa4AE=,tag:ULLvjbmmCvoRf+DzucTTqQ==,type:str]",
		"version": "3.12.2"
	}
}
