{
	"data": "ENC[AES256_GCM,data:meEcIOurgFIeVMqec1rRX8owlXHti/FvitPRdE7cnbe3Mk/oX65hspldd/yw1u5SNQ==,iv:pJnE3WAtqjfuH8SoCFDMyY09T4T9rzX2jVBbQbgXJoE=,tag:HyQVplrubAK7S8I3QfmgYw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc0NGVkd3U2ZVa2I3WXBr\nazRWNzJ6KzRrRVlObG1vVGdyYXliVWFkcmlZClo1RjZnVkVnVWdKU0Q5Ri8xOUVv\nRFlybkdIZ0QraW1BczlYcTBEZzNwVzgKLS0tIC9tQXZFeDZUUTR1OTc3VmNDSFRx\nMU1RN2R2VmdrVmFVNWkzbTdzWUtnd2cKu0tQ6xnkTeiS4vuZI0gkNLxsJitbUUGk\nCeGaFCG3OlgONIfE6l4s4Kxo6QjmlH9PyjA/WjyvCmnJx4pT2YEu2w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-05T13:21:13Z",
		"mac": "ENC[AES256_GCM,data:8B14JE5ujQUvyrmY6IbYTQG50DAl/AcmMytLMkwvxI6/nEA7Eq1A6N8HkM9wdTI9+kZq/WW778mR9LbdPcwyo4ilPYQQzDk3Jldmf5sJrz+JpcGAhumbUfDl75xetISmUFAnF+vAR6mB3/vp6ewISFbT4lguRLej5++XCUZ71U0=,iv:sv8SlhaPYUB7tgGllFDFRmIGmYh2ew2Je9wJUuLAI00=,tag:fc5/nHIPHe5i3/U0f67kHw==,type:str]",
		"version": "3.12.2"
	}
}