{
	"data": "ENC[AES256_GCM,data:aeRL+hf1JARDNWijsGRn9m3ic/pX+EuUzjsUl2PSdj9ELmy0CjoCw79AcOIWFJdigU+l5E24XTB4IoexAg==,iv:n84d/wxbpLzrZY6++riSPxEBzpgVA97OgAbrTTYR7ng=,tag:YVGXXIlSIKy6TFIOA6E9Ig==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcGpnWW82VzIvLzZTWllr\ndUI2b09UTHdoUWJrblY4VGhoVldDQ0NXM2lzClJmUjF3MVBsdEtwYkw3REh4UHBj\nc094WEptaTFXMEFtK01xK29LVE94TW8KLS0tIDErVGNaUzJXU05MYklYNE9VcEhl\nMmlLbFBQcm1vbEpLQXBaY0JRa2NPcUUKgSDEi6vP+M2Z0+E/XCMMLca85I6vjC54\nDMNz5WWPZ+RQb61QgO5Cm7Cob4P8VHozQSJQ0ZbiOvcuMjxeu4ZWnQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-12T11:40:10Z",
		"mac": "ENC[AES256_GCM,data:vUZmluJFA5S7zZBMFnkOIsjVYXmn1PZWkzxbyzAk/IAPU/fUiX/UhjhFV3Do1EDMKzH6WKv35XZFUx0WAox8RKpzlH8zQH8UlsL402JmlTOIXa7fwe/8/xTzZ5mdmXevpJa0DNIwVhRa52OvdEJ6uoKfXhm7xc6kEFB1cbY18LY=,iv:vSYkrG1i9uuVHp97Jotz3NvwLgMZ6n9F2ki4z0XCoKo=,tag:O9Drbq5KmUUjBxRaWW4B0g==,type:str]",
		"version": "3.12.2"
	}
}
