{
	"data": "ENC[AES256_GCM,data:hiQ2tvFv+47XVFnfLxnOJxE/GBvyiZ8016ChIJgplSOKRfmFN+OMhqQNeI5xIITLe9UbDyRcwAZstUQ8dGDre8ReCdu1VvjIOLAS832QpPp4DjN9l1QD35XEUIa6hkRfId+JGl+22COMWfpXZG8tYAX7kYF1iFpcnERBfb6lHBrvNavCAchc4pw=,iv:pR0S2XFwwRUUZf9K0lSgShirxb0yKXDUYtc2fmE+lnk=,tag:nh1SrLQo9qaSQDVT8OKlFQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWG5OZFlXNEdHbHI5Tk9l\nTk9hU1JZbks4aXgzVWU5dlQ5c2xTNTNUZFhJCm1IUFowOUV5Vy9sZGt6bUFwNjl2\ndWd1WFdRMC9UcDhTcVN1c3Z0WU1naEUKLS0tIHZ6T0VIazZvZU9KNndZMnVuZkpK\nVmNiNHNlT0Y3TlZ4VVcvR1BXalRqL2MKnWnz+fEYyoXJa1/sRjE6/kybAF7/Smvr\nMehEhID/AIrp1MV1DUrrDxYt1Q+XimuCmpPQB+xr4o84iyFEePxafw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-05T06:39:28Z",
		"mac": "ENC[AES256_GCM,data:Dc9gCchxVrgh3T0D/8CCzoQHJHkSTj1aIF18qRVdrBrdSiaaBm4XStDJcTXTvE9Gp4kOcUomNWWCw+cgCKwzvoFrDne6HIStgmPrXQ1o7VqcwolQeKhxGx9vYcLjo9XWbmal5QTR6hPubZW4S1lttuWsEq8uIU8EFjjIpJVwQnM=,iv:V7Rd2Ebb6AcAERo6w/TCvL0Eti+3RuqhaSPIcYw8NtA=,tag:GumBraumPfjJFGobkpSnVQ==,type:str]",
		"version": "3.12.2"
	}
}