name: Deploy

on:
  push:
    paths:
      - '**'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Changed Files
        uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 1
          dir_names_exclude_current_dir: true
          files_ignore: '.*/**'
          matrix: true

  deploy:
    if: needs.changed-files.outputs.matrix != '[]'
    needs: [changed-files]
    runs-on: [self-hosted, "${{ matrix.server }}"]
    strategy:
      fail-fast: false
      matrix:
        server: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    env:
      SERVER: ${{ matrix.server }}
      SOPS_AGE_KEY: ${{ secrets[format('AGE_KEY_{0}', matrix.server)] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
      - name: Decrypt Files
        run: find "$SERVER" -type f | xargs grep -l 'sops:' | xargs -r sops --decrypt --in-place
      - name: Deploy Compose Apps
        run: |
          find "$SERVER" -maxdepth 2 -name "compose.json" | while read -r f; do
            APP=$(basename "$(dirname "$f")")
            if curl -fks -H "Authorization: Bearer $TRUENAS_API_KEY" -H "Content-Type: application/json" -X PUT "$TRUENAS_HOST/api/v2.0/app/$APP" -d @"$f"; then
              echo "✓ $APP updated"
            else
              curl -fks -H "Authorization: Bearer $TRUENAS_API_KEY" -H "Content-Type: application/json" -X POST "$TRUENAS_HOST/api/v2.0/app" -d @"$f"
              echo "✓ $APP created"
            fi
          done
      - name: Push Config Files
        run: |
          find "$SERVER" -mindepth 3 -type f ! -name "compose.yaml" ! -name "override.json" | while read -r f; do
            CONTAINER_DIR="$(echo "$f" | cut -d'/' -f1-3)/"
            APP=$(basename "$(dirname "$CONTAINER_DIR")")
            SERVICE=$(basename "$CONTAINER_DIR")
            CONTAINER=$(docker ps --format '{{.Names}}' | grep "^ix-${APP}-${SERVICE}-")
            if [ -n "$CONTAINER" ]; then
              docker cp "$f" "$CONTAINER:/${f#"$CONTAINER_DIR"}"
              echo "✓ $CONTAINER:/${f#"$CONTAINER_DIR"}"
            else
              echo "⚠ no container found matching ix-${APP}-${SERVICE}-*"
            fi
          done
      - name: Update App Environments & Labels
        run: |
          find "$SERVER" -name "override.json" | while read -r f; do
            APP=$(basename "$(dirname "$f")")
            curl -fks -H "Authorization: Bearer $TRUENAS_API_KEY" -H "Content-Type: application/json" -X PUT "$TRUENAS_HOST/api/v2.0/app/$APP" -d @"$f"
            echo "✓ $APP"
          done
